package com.pos.security;

public enum Permission {
    VIEW_DASHBOARD,
    VIEW_REPORTS,
    VIEW_PRODUCTS,
    MANAGE_PRODUCTS,
    VIEW_CUSTOMERS,
    MANAGE_CUSTOMERS,
    VIEW_SALES,
    CREATE_SALES,
    PROCESS_PAYMENTS,
    MANAGE_USERS,
    VIEW_AUDIT_LOGS,
    MANAGE_EXPENSES,
    MANAGE_REFUNDS,
    MANAGE_SUPPLIERS,
    MANAGE_SHIFTS
}
